---

- name: Ensure FTP_PATH exists
  file:
    path:    "{{ FTP_PATH }}"
    state:   directory
    recurse: yes

- name: Create ftp group
  group:
    name:  "{{ FTP_USER }}"
    gid:   "{{ FTP_GID }}"

- name: Create ftp user
  user:
    name:     "{{ FTP_USER }}"
    uid:      "{{ FTP_UID }}"
    group:    "{{ FTP_USER }}"
    shell:    "/bin/bash"
    home:     "{{ FTP_PATH }}"
    password: "{{ FTP_PASSWORD |password_hash('sha512') }}"

- name: Ensure FTP_PATH exists
  file:
    path:    "{{ FTP_PATH }}"
    state:   directory
    recurse: yes
    owner:   "{{ FTP_UID }}"
    group:   "{{ FTP_GID }}"
  ignore_errors: true
